// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Feed struct {
	ID                  interface{}
	Name                string
	Url                 string
	ItemSelector        sql.NullString
	TitleSelector       sql.NullString
	DescriptionSelector sql.NullString
	CreatedAt           sql.NullTime
	CreatedUp           sql.NullTime
	LinkSelector        sql.NullString
}
