// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Feed struct {
	ID                  int64          `json:"id"`
	Name                string         `json:"name"`
	Url                 string         `json:"url"`
	ItemSelector        sql.NullString `json:"item_selector"`
	TitleSelector       sql.NullString `json:"title_selector"`
	LinkSelector        sql.NullString `json:"link_selector"`
	DescriptionSelector sql.NullString `json:"description_selector"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	LastRefresh         sql.NullTime   `json:"last_refresh"`
}

type FeedItem struct {
	ID          int64          `json:"id"`
	FeedID      int64          `json:"feed_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Link        string         `json:"link"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
