// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Feed struct {
	ID                  int64
	Name                string
	Url                 string
	ItemSelector        sql.NullString
	TitleSelector       sql.NullString
	LinkSelector        sql.NullString
	DescriptionSelector sql.NullString
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type FeedItem struct {
	ID          int64
	FeedID      int64
	Title       string
	Description sql.NullString
	Link        string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
