// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const getFeed = `-- name: GetFeed :one
SELECT id, name, url, item_selector, title_selector, description_selector, created_at, created_up, link_selector FROM feeds
WHERE id = ? LIMIT 1
`

func (q *Queries) GetFeed(ctx context.Context, id interface{}) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.ItemSelector,
		&i.TitleSelector,
		&i.DescriptionSelector,
		&i.CreatedAt,
		&i.CreatedUp,
		&i.LinkSelector,
	)
	return i, err
}

const getFirstFeed = `-- name: GetFirstFeed :one
select id, name, url, item_selector, title_selector, description_selector, created_at, created_up, link_selector from feeds limit 1
`

func (q *Queries) GetFirstFeed(ctx context.Context) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFirstFeed)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.ItemSelector,
		&i.TitleSelector,
		&i.DescriptionSelector,
		&i.CreatedAt,
		&i.CreatedUp,
		&i.LinkSelector,
	)
	return i, err
}
